site_name: py-motmetrics 
site_url: https://py-motmetrics.github.io

repo_name: py-motmetrics 
repo_url: https://github.com/cheind/py-motmetrics

nav:
  - home:
    - home: home.md

theme:
  name: material
  language: 'en'
  palette:
    primary: 'Teal'
    accent: 'Teal'
  feature:
    tabs: true
  font:
    text: 'Noto Sans'
    code: 'Cascadia Code'

extra:
  manifest: 'manifest.webmanifest'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: True
      noclasses: True
      pygments_style: monokai
  - def_list
  - footnotes
  - mdx_math
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "#"

plugins:
  - search
  - awesome-pages
  # - git-committers